/**
 *
 * @author kaira
 */
public class YouLost extends javax.swing.JFrame {

    /**
     * Creates new form YouLost
     */
    public YouLost() {
        initComponents();
        //to center the window
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLost = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(530, 560));
        setPreferredSize(new java.awt.Dimension(530, 560));
        setResizable(false);
        getContentPane().setLayout(null);

        lblLost.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lblLost.setForeground(new java.awt.Color(255, 255, 255));
        lblLost.setText("You Lost!");
        getContentPane().add(lblLost);
        lblLost.setBounds(300, 10, 230, 70);

        btnContinue.setBackground(new java.awt.Color(0, 0, 0));
        btnContinue.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue);
        btnContinue.setBounds(370, 470, 140, 40);

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YouLost.jpg"))); // NOI18N
        getContentPane().add(lblBg);
        lblBg.setBounds(0, 0, 530, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        dispose();
        Retry form1 = new Retry();
        form1.setVisible(true);
    }//GEN-LAST:event_btnContinueActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouLost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouLost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblLost;
    // End of variables declaration//GEN-END:variables
}
