/**
 *
 * @author kaira
 */
public class YouWon extends javax.swing.JFrame {

    /**
     * Creates new form YouWon
     */
    public YouWon() {
        initComponents();
        //to centeer the window
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWon = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Won");
        setMaximumSize(new java.awt.Dimension(800, 416));
        setMinimumSize(new java.awt.Dimension(800, 416));
        setPreferredSize(new java.awt.Dimension(800, 416));
        setResizable(false);
        getContentPane().setLayout(null);

        lblWon.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lblWon.setText("You Won !");
        getContentPane().add(lblWon);
        lblWon.setBounds(120, 250, 250, 60);

        btnContinue.setBackground(javax.swing.UIManager.getDefaults().getColor("tab_highlight_header"));
        btnContinue.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue);
        btnContinue.setBounds(580, 300, 140, 40);

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YouWon.jpg"))); // NOI18N
        getContentPane().add(lblBg);
        lblBg.setBounds(0, 0, 800, 416);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        dispose();
        Retry form1 = new Retry();
        form1.setVisible(true);
    }//GEN-LAST:event_btnContinueActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouWon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblWon;
    // End of variables declaration//GEN-END:variables
}
